version: "3"
services:
  api:
    image: covid-detection-app
    ports: 
      - "8080:8000" 
    volumes:
      - ./models:/app/models/

  locust:
    image: locust
    ports: 
      - "8089:8089"
    # volumes: 
    #   - ./test/test_load_server:/locust 
    command: -f locustfile.py


networks:
  fastapi-locust-network:
    driver: bridge